# Generated by Django 5.0.6 on 2024-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('userName', models.CharField(max_length=200, verbose_name='Username')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('contraseña', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['created'],
            },
        ),
    ]
