# Generated by Django 5.0.6 on 2024-10-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subastas',
            fields=[
                ('idSubasta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Subasta')),
                ('MontoInicial', models.FloatField(verbose_name='Monto Inicial')),
                ('FechaHoraInicial', models.DateTimeField(verbose_name='Fecha y Hora Inicial')),
                ('FechaHoraFinal', models.DateTimeField(verbose_name='Fecha y Hora Final')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('IdArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo', verbose_name='ID Artículo')),
            ],
            options={
                'verbose_name': 'Subasta',
                'verbose_name_plural': 'Subastas',
                'ordering': ['FechaHoraInicial'],
            },
        ),
    ]
